# config/packages/notifier.yaml
framework:
  notifier:
    chatter_transports: ~
    texter_transports:
      vonage: '%env(VONAGE_DSN)%'
    channel_policy:
      urgent: ['sms/vonage']
      high: ['sms/vonage']
      medium: ['email']
      low: ['email']
    admin_recipients:
      - { email: admin@example.com }