parameters:
  images_directory: '%kernel.project_dir%/public/uploads/images'
  open_weather_api_key: '%env(OPEN_WEATHER_API_KEY)%'
  app.gemini_api_key: '%env(GEMINI_API_KEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\WeatherService:
    arguments:
      $openWeatherApiKey: '%open_weather_api_key%'
