parameters:
  images_directory: '%kernel.project_dir%/public/uploads/images'
  openweather_api_key: '%env(OPENWEATHER_API_KEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $images_directory: '%images_directory%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\WeatherService:
    arguments:
      $apiKey: '%openweather_api_key%'

  App\Service\DiagnosticAiService:
    arguments:
      $httpClient: '@http_client'
      $logger: '@logger'

  App\Service\PlantNetService:
    arguments:
      $httpClient: '@http_client'
      $logger: '@logger'
      $plantNetApiKey: '%env(PLANTNET_API_KEY)%'

  App\Doctrine\Migrations\SimpleTableMetadataStorage:
    arguments:
      $connection: '@doctrine.dbal.default_connection'